# Generated by Django 3.1.5 on 2021-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube',
            field=models.CharField(default='https://www.youtube.com/', max_length=250),
            preserve_default=False,
        ),
    ]
